Iterate on I/O
shinypb/tsys.js pull request #1
Opened 2022-06-28 04:08 UTC by shinypb

Lots more to nail down, but this feels like an improvement. Thoughts?

2022-06-28 15:41 UTC, jamie-nxtgencare requested changes

2022-06-28 15:41 UTC, jamie-nxtgencare commented on TSYS.md
> +> ❗️ There's currently nothing preventing a second interrupt from happening while the first one is still being processed, so,we probably should have a way to disable interrupts—otherwise two back-to-
Lose the first interrupt, or just not register the second since they are disabled?

Should interrupts for each device be buffered and trigger when the handler is finished executing? (I see there is mention of keyboard buffering, does this happen in the "device"?)

What prevents denial of service by device input overload? Even with a max buffer size for an input device, someone banging on a keyboard will keep interrupting the normal execution of the program.

Or worse -- what if the future I/O device is, I don't know, a game controller, and the inputs are constant.

2022-06-28 15:41 UTC, jamie-nxtgencare commented on TSYS.md
> +- Code at `0x83` is the entrypoint for the interrupt handler. It should consist of a JMP instruction pointing to the interrupt handler.
Memory layout spreadsheet has `0x84` for this entry point.

2022-06-28 15:41 UTC, jamie-nxtgencare commented on TSYS.md
> +All I/O is done through memory mapping. Up to 16 I/O devices are supported.
Should be room for 31 devices? 128 bytes / 4 bytes per device = 32, minus one device for control bytes.

Of course leaving some reserved room for additional features makes sense as well.

[edit] Nevermind, I see below we're limited in device count by the 3 bit high nibble recent interrupt status.

2022-06-28 15:41 UTC, jamie-nxtgencare commented on TSYS.md
> +- Low nibble (bits 0-3): indicates whether I/O interrupts are enabled for the given Thread.
Just for clarity's sake, `0x02` would be interrupts enabled for Thread 0 and Thread 1, and `0x05` would be interrupts enabled for Thread #0 and Thread #4? I'm assuming these are bit flags, based on `0x01` below meaning interrupts enabled only for Thread #0.

2022-06-28 15:41 UTC, jamie-nxtgencare commented on TSYS.md
> +		> ❓ How would well-behaved code go about obtaining ownership without accidentally clobbering another thread? Imagine Thread #2 wants to set this value and gets interrupted partway through the acqui
An atomic check and set operation would be my first thought for managing a semaphore-like ownership bit. Otherwise, since we could have contention between more than 2 threads, I think the [Filter algorithm (Peterson's Algorithm for > 2 processes)](https://en.wikipedia.org/wiki/Peterson%27s_algorithm#Filter_algorithm:_Peterson's_algorithm_for_more_than_two_processes) should enforce mutex access to the device.

I do wonder what happens to a thread that requests a device but can't acquire it though. Should be there an access queue? Doesn't really sound like a 1970s style solution though...

2022-06-28 15:41 UTC, jamie-nxtgencare commented on TSYS.md
> +		> ❓ Perhaps I/O device ownership should be more than a convention, and the system should `HALT` if a thread attempts to read the I/O range of a device that they are not the owner of?
This feels consistent with the join to HALT on JMP < `0x80`, even if not the same sort of scenario. Both feel "illegal" to me.

2022-06-28 15:41 UTC, jamie-nxtgencare commented on TSYS.md
> +0. The recipient thread's program counter is changed to `0x83` (the interrupt handler).
Second reference to `0x83` while `0x84` is in the spreadsheet. Although see below where I ask questions about the interrupt handler in general.

2022-06-28 15:41 UTC, jamie-nxtgencare commented on TSYS.md
> +- Device 2 (`0x08`): keyboard
`0x0c` I believe.

2022-06-28 15:41 UTC, jamie-nxtgencare commented on TSYS.md
> +It is the responsibility of the interrupt handler to restore the previous value of the current thread's program counter from memory location `0x01—0x02` once it has finished servicing the interrupt.
* How does the interrupt location get registered?
* Is that part of the new instruction? Is it formally part of the spec and permanently in that location?
* What does "servicing the interrupt look like"? Is it program code defined?

I'm picturing a new instruction that would have to specify a device and a label for an interrupt handler label/offset. Is that why it doesn't really matter where the handler location doesn't matter?

2022-06-28 15:43 UTC, shinypb commented on TSYS.md
> +> ❗️ There's currently nothing preventing a second interrupt from happening while the first one is still being processed, so,we probably should have a way to disable interrupts—otherwise two back-to-
If interrupts are disabled, you'd lose the second interrupt—but presumably the device's status flags would still be set indicating that data was waiting, so you could theoretically have your interrupt handler sweep through all of the devices to see which ones need service. That means you could “catch up” later.

Keyboard buffering would be at the device layer.

No provision against denial of service from misconfigured devices. That seems like a fact of life for old/simple computers.

2022-06-28 15:47 UTC, shinypb commented on TSYS.md
> +- Low nibble (bits 0-3): indicates whether I/O interrupts are enabled for the given Thread.
The bottom four bits are on/off flags for each thread:

````
Are interrupts enabled for...

Thread #0-----------+
Thread #1 --------+ |
Thread #2 ------+ | |
Thread #3 ----+ | | |
              | | | |
              v v v v
Bits: 0 0 0 0 0 0 0 0
````

2022-06-28 16:27 UTC, jamie-nxtgencare commented on TSYS.md
> +> ❗️ There's currently nothing preventing a second interrupt from happening while the first one is still being processed, so,we probably should have a way to disable interrupts—otherwise two back-to-
Gotcha, I was just confused because you wrote

> just "lose" the first interrupt

Just wanted to clarify that the first would be unaffected.

2022-06-28 16:32 UTC, jamie-nxtgencare commented on TSYS.md
> +- Low nibble (bits 0-3): indicates whether I/O interrupts are enabled for the given Thread.
Okay, that's what I figured, I just managed to cram as many errors into my question as possible ;)

2022-06-29 17:55 UTC, jamie-nxtgencare commented on TSYS.md
> +		> ❓ How would well-behaved code go about obtaining ownership without accidentally clobbering another thread? Imagine Thread #2 wants to set this value and gets interrupted partway through the acqui
I've got a PR in that is making use of a new `BTS` (`MBTS`, memory bit-test-and-set) instruction that should handle this.

2022-07-01 02:39 UTC, shinypb commented on TSYS.md
> +- Code at `0x83` is the entrypoint for the interrupt handler. It should consist of a JMP instruction pointing to the interrupt handler.
Spreadsheet was correct, thanks

2022-07-01 02:40 UTC, shinypb commented on TSYS.md
> +- Device 2 (`0x08`): keyboard
Fixed, thanks

2022-07-01 02:41 UTC, merged